### ISSUE TITLE
Reeder 5

### ISSUE THREAD

**Issue by Vinestou** [javerous/freshrss-greader-redate#1]
Hi, is this still needed for Reeder 5?

**Comment by ryoku-cha** [comment]
No, it is no longer needed with Reeder 5.

I installed FreshRSS a month ago and use it since then. I had the same question at that time, as Reeder 4 still had this issue (which i was using up to that time). I then bought Reeder 5, hoping this was solved there. And it turned out it was.

Here are two Screenshots from a month ago. Showing the same Feed (FreshRSS). While Reeder 4 shows the time the Feed was fetched, Reeder 5 shows the Time and Date the individual Articles where released.

**Reeder 4**
![reeder_4](https://user-images.githubusercontent.com/4163632/173416527-0bd890b7-19e1-4975-9b62-6e7c77e8e3bc.jpg)

**Reeder 5**
![reeder_5](https://user-images.githubusercontent.com/4163632/173416534-dbec15e4-ce85-4baf-8706-2f39c68aed0e.jpg)

**Comment by javerous** [comment]
@ryoku-cha Good to know, thank you. And sorry @Vinestou, I totally forgot to answer to you (I didn't even test if it was still necessary, even if I updated on Reeder 5 for a while 😅)

**Comment by ryoku-cha** [comment]
@javerous thanks for the fast Reply. I think you can close this issue now, as the question is now answered.

I just created a Pull Request for the README.md from FreshRSS, trying to clarify this.
Maybe you want to update your Readme as well. More important in my view is the one from FreshRSS, as that one led me here initially.
